/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuxinbo_resourcemanage_jni_ImageMagick */

#ifndef _Included_com_wuxinbo_resourcemanage_jni_ImageMagick
#define _Included_com_wuxinbo_resourcemanage_jni_ImageMagick
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wuxinbo_resourcemanage_jni_ImageMagick
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_ImageMagick_init
  (JNIEnv *, jclass);

/*
 * Class:     com_wuxinbo_resourcemanage_jni_ImageMagick
 * Method:    resize
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wuxinbo_resourcemanage_jni_ImageMagick_resize
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_wuxinbo_resourcemanage_jni_ImageMagick
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_ImageMagick_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
