/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuxinbo_resourcemanage_jni_FileWatch */

#ifndef _Included_com_wuxinbo_resourcemanage_jni_FileWatch
#define _Included_com_wuxinbo_resourcemanage_jni_FileWatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuxinbo_resourcemanage_jni_FileWatch
 * Method:    watchDir
 * Signature: (Ljava/lang/String;)Lcom/wuxinbo/resourcemanage/model/FileChangeNotify;
 */
JNIEXPORT jobject JNICALL Java_com_wuxinbo_resourcemanage_jni_FileWatch_watchDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
