/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuxinbo_resourcemanage_jni_FileWatch */
#include <memory>
#ifndef _Included_com_wuxinbo_resourcemanage_jni_FileWatch
#define _Included_com_wuxinbo_resourcemanage_jni_FileWatch
#ifdef __cplusplus
extern "C" {
#endif
struct FileNotify {
    unsigned long action;
    std::unique_ptr<char[]> filePathPtr;
    const char * filePath;
};
/*
 * Class:     com_wuxinbo_resourcemanage_jni_FileWatch
 * Method:    watchDir
 * Signature: (Ljava/lang/String;)Lcom/wuxinbo/resourcemanage/model/FileChangeNotify;
 */
JNIEXPORT jobject JNICALL Java_com_wuxinbo_resourcemanage_jni_FileWatch_watchDir
  (JNIEnv *, jobject, jstring);

JNIEXPORT void watchDirChange(const char * dirName,FileNotify &fileNotify);

#ifdef __cplusplus
}

#endif
#endif
