/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_wuxinbo_resourcemanage_jni_TCPClient */

#ifndef _Included_com_wuxinbo_resourcemanage_jni_TCPServerClient
#define _Included_com_wuxinbo_resourcemanage_jni_TCPServerClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuxinbo_resourcemanage_jni_TCPClient
 * Method:    sendUTFData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_TCPServerClient_sendUTFData
  (JNIEnv *, jobject, jstring, jstring);
/**
* 发送数据到客户端
* @param address 客户端地址 ip:port
*/
  JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_TCPServerClient_sendUTFDataToClient
  (JNIEnv *, jobject, jstring, jstring);
 /*
   启动tcp server
 * Class:     com_wuxinbo_resourcemanage_jni_TCPServerClient
 * Method:    startServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_TCPServerClient_startServer
(JNIEnv *, jclass, jint); 
#ifdef __cplusplus
}
#endif
#endif
