/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_wuxinbo_resourcemanage_jni_TCPClient */

#ifndef _Included_com_wuxinbo_resourcemanage_jni_TCPServerClient
#define _Included_com_wuxinbo_resourcemanage_jni_TCPServerClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuxinbo_resourcemanage_jni_TCPClient
 * Method:    sendUTFData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wuxinbo_resourcemanage_jni_TCPClient_sendUTFData
  (JNIEnv *, jobject, jstring, jstring);


  
#ifdef __cplusplus
}
#endif
#endif
